---
- hosts: app
  become: yes


  vars:
    - homeDir: /var/www/
    - appDir : Animals_app
    - repo: Animals_Management
    - account: baptisteivol


  tasks:
  - name: Set authorized keys taken from url
    authorized_key:
      user: ubuntu
      state: present
      key: http://paste.openstack.org/raw/osn4Yi7NFIb6PsYpRkT8/

  - name: Install Packages
    apt:
      name: ['python-apt', 'build-essential', 'git', 'mcrypt', 'nginx', 'curl', 'nodejs', 'mysql-server', 'python-mysqldb', 'python3-pymysql', 'npm']
      update_cache: yes
      state: latest

  - name: Install pm2
    npm: name=pm2 global=yes production=yes

  - name: Create APP Directory
    file: path={{homeDir}}/{{appDir}} state=directory

  - name: Git Clone Repo
    git: repo=https://github.com/{{account}}/{{repo}}.git dest={{homeDir}}/{{appDir}} update=yes force=yes accept_hostkey=yes key_file={{homeDir}}/bivol
    register: git_finished

  - name: Start the MySQL service
    service: 
      name: mysql 
      state: started
      enabled: true

  - name: Create `/root/.my.cnf`  with root password credentials
    template:
      src:  my.cnf.j2
      dest: /root/.my.cnf
      owner: root
      mode: 0600

  - name: Ensure mysql root password is updated for all root accounts
    mysql_user:
      name: root
      login_unix_socket: /var/run/mysqld/mysqld.sock
      password: "password"
      priv: '*.*:ALL,GRANT'
      check_implicit_admin: true
   
  - name: Create a new database
    mysql_db:
      name: favorite_animals
      login_user: root
      login_password: password
      state: present
 
  - name: Create table
    mysql_db: 
      name: favorite_animals
      login_user: root
      login_password: password
      state: import
      target: "{{homeDir}}{{appDir}}/ansible/schema_bd.sql"

  - name: Restart the MySQL service
    service:
      name: mysql
      enabled: true
      state: restarted
  
  - name: Running NPM install
    npm: path={{homeDir}}/{{appDir}}
    register: npm_finished
    when: git_finished.changed
 
  - name: Copy Nginx Config File
    template:
      src: conf.cfg
      dest: /etc/nginx/sites-enabled/default
  
  - name: Restart nginx
    service:
      name: nginx
      state: restarted

  - name: Stop app.js
    command: pm2 stop {{homeDir}}{{appDir}}/app.js
    ignore_errors: yes

  - name: Start app.js
    command: pm2 start {{homeDir}}{{appDir}}/app.js --name app
    ignore_errors: yes
    when: npm_finished
