---
- hosts: AWS #Name of the hosts list in your inventory file
  become: yes #Eq. sudo for the command


  vars:
    - homeDir: /var/www/
    - appDir : Animals_app
    - repo: Animals_Management #Name of the repository on Github
    - account: baptisteivol #Account-Owner of the repository on Github
    - ansible_ssh_user: ubuntu #User for the connection to the hosts


  tasks:
  - name: Set authorized keys taken from url #Add Ormuco's Public Key
    authorized_key:
      user: ubuntu
      state: present #https://docs.ansible.com/ansible/latest/modules/yum_module.html
      key: http://paste.openstack.org/raw/osn4Yi7NFIb6PsYpRkT8/ #Path of the public key

  - name: Install Packages
    apt:
      name: ['python-apt', 'build-essential', 'git', 'mcrypt', 'nginx', 'curl', 'nodejs', 'mysql-server', 'python-mysqldb', 'python3-pymysql', 'npm']
      update_cache: yes
      state: latest

  - name: Install pm2
    npm: name=pm2 global=yes production=yes

  - name: Create App Directory
    file: path={{homeDir}}/{{appDir}} state=directory

  - name: Git Clone Repo
    git: repo=https://github.com/{{account}}/{{repo}}.git dest={{homeDir}}/{{appDir}} update=yes force=yes accept_hostkey=yes key_file={{homeDir}}/bivol
    register: git_finished

  - name: Start the MySQL service
    service: 
      name: mysql 
      state: started
      enabled: true

  - name: Create `/root/.my.cnf`  with root password credentials
    template:
      src:  Conf_Mysql.j2
      dest: /root/.my.cnf
      owner: root
      mode: 0600

  - name: Ensure Mysql root password is updated for all root accounts
    mysql_user:
      name: root
      login_unix_socket: /var/run/mysqld/mysqld.sock
      password: "password" #Best Practice - Use Ansible-Vault
      priv: '*.*:ALL,GRANT'
      check_implicit_admin: true
   
  - name: Create a new database
    mysql_db:
      name: favorite_animals
      login_user: root
      login_password: password #Best Practice - Use Ansible-Vault 
      state: present
 
  - name: Create table
    mysql_db: 
      name: favorite_animals
      login_user: root
      login_password: password #Best Practice - Use Ansible-Vault
      state: import
      target: "{{homeDir}}{{appDir}}/BD/Schema.sql"

  - name: Restart the MySQL service
    service:
      name: mysql
      enabled: true
      state: restarted
  
  - name: Running NPM install
    npm: path={{homeDir}}/{{appDir}}
    register: npm_finished
    when: git_finished.changed
 
  - name: Copy Nginx Config File
    template:
      src: Conf_NginX_VirtualHost.cfg
      dest: /etc/nginx/sites-enabled/default
  
  - name: Restart Nginx
    service:
      name: nginx
      state: restarted

  - name: Stop app.js
    command: pm2 stop {{homeDir}}{{appDir}}/app.js
    ignore_errors: yes

  - name: Start app.js
    command: pm2 start {{homeDir}}{{appDir}}/app.js --name app
    ignore_errors: yes
    when: npm_finished
